titles:
  en: Tags
  ru: Таги
record_file:
  name: "tags.json"
  type: "map[id]map[field]any"
  format: json
columns:
  title:
    type: string
    locale: en
  titles:
    type: "map[locale]string"
    required: true
