titles:
  en: Tags
  ru: Таги

record_file:
  name: "tags.json"
  type: "map[id]map[field]any"
  format: json

columns:

  title:
    type: string
    locale: en
    required: true

  titles:
    type: "map[locale]string"
    required: false

  description:
    type: string
    required: false
