version: 2

project_name: ingitdb

before:
  hooks:
    - go mod tidy

builds:
  - id: ingitdb-unix
    main: ./cmd/ingitdb
    binary: ingitdb
    env: [CGO_ENABLED=0]
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

  - id: ingitdb-windows
    main: ./cmd/ingitdb
    binary: ingitdb
    env: [CGO_ENABLED=0]
    goos: [windows]
    goarch: [amd64]
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: tarball
    formats: [ tar.gz ]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    ids: [ingitdb-unix]
    files:
      - README.md
      - LICENSE*

  - id: zip
    formats: [ zip ]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    ids: [ingitdb-windows]

checksum:
  name_template: checksums.txt

brews:
  - name: ingitdb
    ids: [ingitdb-unix]
    repository:
      owner: ingitdb
      name: homebrew-cli
      token: "{{ .Env.GORELEASER_GITHUB_TOKEN }}"
    homepage: https://github.com/ingitdb/ingitdb-cli
    description: CLI for inGitDB

release:
  github:
    owner: ingitdb
    name: ingitdb-cli
