# You can link a specific collection or a directory with collections
rootCollections:
  countries: geo/countries
  todo: todo/*

# `languages` list supported languages should preferably use `ISO 639-1`
#  or alternatively `IERF BCP 47` (`RFC 5646` / `RFC 4647`).
#
# Examples:
#  - required: en
#  - optional: ru
#
# The required languages should be before the optional ones.
# Language selector will show languages in order defined in this list.
languages:
  - required: en
  - required: fr
  - required: es
  - optional: ru
