titles:
  en: Settlements
  ru: Населённые пункты
  es: Asentamientos
  fr: Établissements
  de: Siedlungen
  zh: 定居点
record_file:
  name: "{$id}.json"
  format: json
  type: "map[string]any"
columns:
  names:
    type: map[locale]string
    required: true
    valueTitle: Name
  population:
    type: int
    title: Population
  area:
    type: float
    title: Area (km²)
