id: "lowerCase(iso_code)"

titles:
  en: Countries
  ru: Страны
  es: Países
  fr: Pays
  de: Länder

record_file:
  name: "{$id}/{$id}.json"
  format: json
  type: "map[string]any"

columns:
  iso_code:
    type: string
    required: true
    length: 2
    checks:
      - ".iso_code === toUpperCase(.iso_code)"

  names:
    type: map[locale]string
    required: true
    titles:
      en: Country
      ru: Страна

  population:
    type: int
    title: Population
    min_value: 0
    max_value: 9 000 000 000

  area:
    type: int
    title: Area (km²)
    min_value: 0

  capital:
    type: string
    required: true

subCollections:
  - def: .ingitdb-subcol.counties.yaml
