titles:
  en: Countries
  ru: Страны
  es: Países
  fr: Pays
  de: Länder
record_file:
  format: json
  name: "{key}.json"
columns:
  names:
    type: map[locale]string
    required: true
    valueTitle: Name
  population:
    type: int
    title: Population
  area:
    type: int
    title: Area (km²)
  capital:
    type: string
    required: true