name: Deploy to Cloud Run
description: Build and deploy the ingitdb server to Google Cloud Run

inputs:
  gcloud_project_id:
    description: Google Cloud project ID
    required: true
  gcloud_region:
    description: Google Cloud region
    required: true
  service_name:
    description: Cloud Run service name
    required: true
  ingitdb_github_oauth_client_id:
    description: GitHub OAuth client ID
    required: true
  ingitdb_github_oauth_callback_url:
    description: GitHub OAuth callback URL
    required: true
  ingitdb_auth_cookie_domain:
    description: Auth cookie domain
    required: true
  ingitdb_auth_api_base_url:
    description: Auth API base URL
    required: true
  ingitdb_auth_cookie_name:
    description: Auth cookie name
    required: false
    default: ingitdb_session
  ingitdb_auth_cookie_secure:
    description: Auth cookie secure flag
    required: false
    default: 'true'
  gcp_oauth_client_secret_name:
    description: GCP secret manager secret name for OAuth client secret
    required: true
  workload_identity_provider:
    description: Workload identity provider URI
    required: true

runs:
  using: composite
  steps:
    - name: Validate required inputs
      shell: bash
      run: |
        set -euo pipefail
        required_inputs=(
          "gcloud_project_id"
          "gcloud_region"
          "service_name"
          "ingitdb_github_oauth_client_id"
          "ingitdb_github_oauth_callback_url"
          "ingitdb_auth_cookie_domain"
          "ingitdb_auth_api_base_url"
          "gcp_oauth_client_secret_name"
          "workload_identity_provider"
        )
        missing=()
        for input_name in "${required_inputs[@]}"; do
          input_var="INPUT_${input_name^^}"
          if [[ -z "${!input_var:-}" ]]; then
            missing+=("$input_name")
          fi
        done
        if (( ${#missing[@]} > 0 )); then
          echo "::error::Missing required inputs: ${missing[*]}"
          exit 1
        fi

    - name: Download latest release binary
      id: release
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        VERSION=$(gh release view --repo ${{ github.repository }} --json tagName --jq '.tagName')
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        ASSET="ingitdb_${VERSION#v}_linux_amd64.tar.gz"
        echo "asset=${ASSET}" >> $GITHUB_OUTPUT
        echo "Deploying ${ASSET} (${VERSION})"
        gh release download "${VERSION}" \
          --repo ${{ github.repository }} \
          --pattern "ingitdb_*_linux_amd64.tar.gz" \
          --output ingitdb_linux_amd64.tar.gz
        tar -xzf ingitdb_linux_amd64.tar.gz ingitdb
        chmod +x ingitdb

    - id: auth
      name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v3
      with:
        service_account: 'deployer2gcloud@${{ inputs.gcloud_project_id }}.iam.gserviceaccount.com'
        workload_identity_provider: ${{ inputs.workload_identity_provider }}

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v3
      with:
        project_id: ${{ inputs.gcloud_project_id }}

    - name: Check if image already exists
      id: image-check
      shell: bash
      run: |
        IMAGE=${{ inputs.gcloud_region }}-docker.pkg.dev/${{ inputs.gcloud_project_id }}/cloud-run/${{ inputs.service_name }}:${{ steps.release.outputs.version }}
        if gcloud artifacts docker images describe "${IMAGE}" --project=${{ inputs.gcloud_project_id }} > /dev/null 2>&1; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "Image ${IMAGE} already exists — skipping build/push/deploy"
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "Image ${IMAGE} not found — will build and deploy"
        fi

    - name: Configure Docker for Artifact Registry
      if: steps.image-check.outputs.exists != 'true'
      shell: bash
      run: gcloud auth configure-docker ${{ inputs.gcloud_region }}-docker.pkg.dev

    - name: Build Docker image
      if: steps.image-check.outputs.exists != 'true'
      shell: bash
      run: |
        docker build \
          -f server/Dockerfile \
          -t ${{ inputs.gcloud_region }}-docker.pkg.dev/${{ inputs.gcloud_project_id }}/cloud-run/${{ inputs.service_name }}:${{ steps.release.outputs.version }} \
          -t ${{ inputs.gcloud_region }}-docker.pkg.dev/${{ inputs.gcloud_project_id }}/cloud-run/${{ inputs.service_name }}:latest \
          .

    - name: Push Docker image
      if: steps.image-check.outputs.exists != 'true'
      shell: bash
      run: |
        docker push ${{ inputs.gcloud_region }}-docker.pkg.dev/${{ inputs.gcloud_project_id }}/cloud-run/${{ inputs.service_name }}:${{ steps.release.outputs.version }}
        docker push ${{ inputs.gcloud_region }}-docker.pkg.dev/${{ inputs.gcloud_project_id }}/cloud-run/${{ inputs.service_name }}:latest

    - name: Deploy to Cloud Run
      if: steps.image-check.outputs.exists != 'true'
      shell: bash
      run: |
        gcloud run deploy ${{ inputs.service_name }} \
          --image=${{ inputs.gcloud_region }}-docker.pkg.dev/${{ inputs.gcloud_project_id }}/cloud-run/${{ inputs.service_name }}:${{ steps.release.outputs.version }} \
          --platform=managed \
          --region=${{ inputs.gcloud_region }} \
          --allow-unauthenticated \
          --min-instances=0 \
          --max-instances=2 \
          --memory=512Mi \
          --cpu=1 \
          --timeout=300 \
          --set-env-vars=INGITDB_GITHUB_OAUTH_CLIENT_ID=${{ inputs.ingitdb_github_oauth_client_id }},INGITDB_GITHUB_OAUTH_CALLBACK_URL=${{ inputs.ingitdb_github_oauth_callback_url }},INGITDB_AUTH_COOKIE_DOMAIN=${{ inputs.ingitdb_auth_cookie_domain }},INGITDB_AUTH_API_BASE_URL=${{ inputs.ingitdb_auth_api_base_url }},INGITDB_AUTH_COOKIE_NAME=${{ inputs.ingitdb_auth_cookie_name }},INGITDB_AUTH_COOKIE_SECURE=${{ inputs.ingitdb_auth_cookie_secure }} \
          --set-secrets=INGITDB_GITHUB_OAUTH_CLIENT_SECRET=${{ inputs.gcp_oauth_client_secret_name }}:latest \
          --project=${{ inputs.gcloud_project_id }}

    - name: Show service URL
      shell: bash
      run: |
        SERVICE_URL=$(gcloud run services describe ${{ inputs.service_name }} --region=${{ inputs.gcloud_region }} --format='value(status.url)')
        echo "Service deployed to: $SERVICE_URL"
