// Code generated by MockGen. DO NOT EDIT.
// Source: cmd/ingitdb/commands/seams.go
//
// Generated by this command:
//
//	mockgen -source=cmd/ingitdb/commands/seams.go -destination=cmd/ingitdb/commands/mocks_test.go -package=commands
//

// Package commands is a generated GoMock package.
package commands

import (
	reflect "reflect"

	dal "github.com/dal-go/dalgo/dal"
	dalgo2ghingitdb "github.com/ingitdb/ingitdb-cli/pkg/dalgo2ghingitdb"
	ingitdb "github.com/ingitdb/ingitdb-cli/pkg/ingitdb"
	materializer "github.com/ingitdb/ingitdb-cli/pkg/ingitdb/materializer"
	gomock "go.uber.org/mock/gomock"
)

// MockGitHubDBFactory is a mock of GitHubDBFactory interface.
type MockGitHubDBFactory struct {
	ctrl     *gomock.Controller
	recorder *MockGitHubDBFactoryMockRecorder
	isgomock struct{}
}

// MockGitHubDBFactoryMockRecorder is the mock recorder for MockGitHubDBFactory.
type MockGitHubDBFactoryMockRecorder struct {
	mock *MockGitHubDBFactory
}

// NewMockGitHubDBFactory creates a new mock instance.
func NewMockGitHubDBFactory(ctrl *gomock.Controller) *MockGitHubDBFactory {
	mock := &MockGitHubDBFactory{ctrl: ctrl}
	mock.recorder = &MockGitHubDBFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitHubDBFactory) EXPECT() *MockGitHubDBFactoryMockRecorder {
	return m.recorder
}

// NewGitHubDBWithDef mocks base method.
func (m *MockGitHubDBFactory) NewGitHubDBWithDef(cfg dalgo2ghingitdb.Config, def *ingitdb.Definition) (dal.DB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewGitHubDBWithDef", cfg, def)
	ret0, _ := ret[0].(dal.DB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewGitHubDBWithDef indicates an expected call of NewGitHubDBWithDef.
func (mr *MockGitHubDBFactoryMockRecorder) NewGitHubDBWithDef(cfg, def any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewGitHubDBWithDef", reflect.TypeOf((*MockGitHubDBFactory)(nil).NewGitHubDBWithDef), cfg, def)
}

// MockGitHubFileReaderFactory is a mock of GitHubFileReaderFactory interface.
type MockGitHubFileReaderFactory struct {
	ctrl     *gomock.Controller
	recorder *MockGitHubFileReaderFactoryMockRecorder
	isgomock struct{}
}

// MockGitHubFileReaderFactoryMockRecorder is the mock recorder for MockGitHubFileReaderFactory.
type MockGitHubFileReaderFactoryMockRecorder struct {
	mock *MockGitHubFileReaderFactory
}

// NewMockGitHubFileReaderFactory creates a new mock instance.
func NewMockGitHubFileReaderFactory(ctrl *gomock.Controller) *MockGitHubFileReaderFactory {
	mock := &MockGitHubFileReaderFactory{ctrl: ctrl}
	mock.recorder = &MockGitHubFileReaderFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitHubFileReaderFactory) EXPECT() *MockGitHubFileReaderFactoryMockRecorder {
	return m.recorder
}

// NewGitHubFileReader mocks base method.
func (m *MockGitHubFileReaderFactory) NewGitHubFileReader(cfg dalgo2ghingitdb.Config) (dalgo2ghingitdb.FileReader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewGitHubFileReader", cfg)
	ret0, _ := ret[0].(dalgo2ghingitdb.FileReader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewGitHubFileReader indicates an expected call of NewGitHubFileReader.
func (mr *MockGitHubFileReaderFactoryMockRecorder) NewGitHubFileReader(cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewGitHubFileReader", reflect.TypeOf((*MockGitHubFileReaderFactory)(nil).NewGitHubFileReader), cfg)
}

// MockViewBuilderFactory is a mock of ViewBuilderFactory interface.
type MockViewBuilderFactory struct {
	ctrl     *gomock.Controller
	recorder *MockViewBuilderFactoryMockRecorder
	isgomock struct{}
}

// MockViewBuilderFactoryMockRecorder is the mock recorder for MockViewBuilderFactory.
type MockViewBuilderFactoryMockRecorder struct {
	mock *MockViewBuilderFactory
}

// NewMockViewBuilderFactory creates a new mock instance.
func NewMockViewBuilderFactory(ctrl *gomock.Controller) *MockViewBuilderFactory {
	mock := &MockViewBuilderFactory{ctrl: ctrl}
	mock.recorder = &MockViewBuilderFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockViewBuilderFactory) EXPECT() *MockViewBuilderFactoryMockRecorder {
	return m.recorder
}

// ViewBuilderForCollection mocks base method.
func (m *MockViewBuilderFactory) ViewBuilderForCollection(colDef *ingitdb.CollectionDef) (materializer.ViewBuilder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ViewBuilderForCollection", colDef)
	ret0, _ := ret[0].(materializer.ViewBuilder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ViewBuilderForCollection indicates an expected call of ViewBuilderForCollection.
func (mr *MockViewBuilderFactoryMockRecorder) ViewBuilderForCollection(colDef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewBuilderForCollection", reflect.TypeOf((*MockViewBuilderFactory)(nil).ViewBuilderForCollection), colDef)
}
